name: Deploy to Amazon EC2 and Lambda

on:
  push:
    branches:
      - main

jobs:
  provision-cloud:
    name: Prepare AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - run: cd terraform && terraform init
      - name: Run terraform
        run: cd terraform && terraform apply -auto-approve -var="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Save terraform state
        uses: EndBug/add-and-commit@v9
        with:
          author_name: terraform
          author_email: ander11110@gmail.com
          message: '[no ci] update terraform state'
          pull: 'origin main'
      - name: Check terraform state
        run: cd terraform && terraform state list
      - run: cd terraform && terraform state show aws_instance.tf_test_ec2
  deploy-server:
    name: Deploy server application
    runs-on: ubuntu-latest
    needs: provision-cloud
    steps:
      - name: connect to server
        run: echo ssh into server and push my server app code
  deploy-serverless:
    name: Deploy serverless application
    runs-on: ubuntu-latest
    needs: provision-cloud
    steps:
      - name: deploy lambda
        run: echo deploy my function
